apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: z9fyz1rlf-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: z9fyz1rlf-go 
  name: z9fyz1rlf-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: z9fyz1rlf-go 
